name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  provider: ^6.1.5  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/1806029.png
    - assets/images/nike logo white.png
    - assets/images/Nike-Logo-Free-PNG-Image.png
    - assets/images/Nike-Logo-PNG-Clipart.png
    - assets/images/pngwing.com (1).png
    - assets/images/pngwing.com (2).png
    - assets/images/pngwing.com (3).png
    - assets/images/pngwing.com (4).png
    - assets/images/pngwing.com.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
